name: Bump version and Release

# How to use notes
# - https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/managing-tags

on:
  push:
    tags:
      - "*"

jobs:
  Bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Get version name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Bump version
        run: npm version ${{env.RELEASE_VERSION}}
      - name: Push to github repository
        run: |
          git commit -m "GitAction: Updated package version to ${{env.RELEASE_VERSION}}"
          git push origin ${{env.RELEASE_VERSION}} --force

  Create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release & Changelog
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GIT_TOKEN }}"
          prerelease: false