name: Bump NPM Version

on:
  push:
    tags:
      - "v*"

jobs:
  Bump:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      
      - name: Checkout@v2
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}

      - name: Bump npm version
        run: npm version ${{env.RELEASE_VERSION}}
